### ISSUE TITLE
Help sought on “Digest value” & “Signature value”

### ISSUE THREAD

**Issue by vikpande** [digidentity/libsaml#158]
@benoist . 

We are doing an integration with DigiD, a digital identity service in the Netherlands, (its similar to authentication service like google or facebook and uses SAML 2.0). 

To authenticate our application to their service ( to allow our users to log in to our application using this DigiD service), we have been asked for an xml with the certificate details, public key info, and some more details. 

While we were able to furnish all the information to them, we could not figure out what do we enter in the below two tags and where do we obtain these values/information from :  
snippet from the entire xml ( for security purpose) :  

------------------------------

<Ds:DigestValue>irsh4GNXQcsbkUmex22XsUejBTXyDdHfaUL/MFFWQHs=</Ds:DigestValue>
</Ds:Reference>
</Ds:SignedInfo>
<Ds:SignatureValue>YJ0V4gCTwRYvgyLnOEvyF2ddwBFwILL4nCpw==</Ds:SignatureValue>
</Ds:Signature>

------------------------------

Note - the value you see in the above xml between these two tags are samples that was provided by the third party provider as a reference. 

We are using "HTTP-Redirect" binding for the connection. 

Any help in this regard is appreciated. thank you. 

Best regards,
vikpande

**Comment by sheffy-kalra** [comment]
Hi Vikas,

Loo into below URL. This may helps you to generate, calculate Digest value and Signature Value.
https://stackoverflow.com/questions/23394654/signing-a-xml-document-with-x509-certificate

**Comment by benoist** [comment]
This library was first created to work with DigiD so it's relatively easy to make it happen. You just need to know what to configure :)

In order to connect to DigiD, you have to deliver the SAML metadata which contains the entity id and the signing and encryption certificates.
The signature value and digest value will be automatically filled in if you sign the Metadata object with your private key.

First make sure you configure your Saml store where the metadata from DigiD is located and your private key is configured

```ruby
Saml.setup do |config|
  config.register_store :file, Saml::ProviderStores::File.new("config/metadata", "config/ssl/key.pem"), default: true
end
```

SAML metadata or entity descriptors can be made like this:

```ruby
  def entity_descriptor
    signing_key_descriptor    = Saml::Elements::KeyDescriptor.new(certificate: "<PEM>", use: 'signing')
    encryption_key_descriptor = Saml::Elements::KeyDescriptor.new(certificate: "<PEM>", use: 'encryption')

    assertion_consumer_service = Saml::Elements::SPSSODescriptor::AssertionConsumerService.new(
        binding:  Saml::ProtocolBinding::HTTP_ARTIFACT,
        index:    0,
        location: "<receive artifact url>"
    )

    single_logout_service = Saml::Elements::SPSSODescriptor::SingleLogoutService.new(
      location: "<receive logout url>",
      binding: Saml::ProtocolBinding::HTTP_REDIRECT
    )

    sp_sso_descriptor = Saml::Elements::SPSSODescriptor.new(
        assertion_consumer_services: [assertion_consumer_service],
        single_logout_services:      [single_logout_service],
        key_descriptors:             [signing_key_descriptor, encryption_key_descriptor]
    )

    entity_descriptor                   = Saml::Elements::EntityDescriptor.new(entity_id: "<entity_id>")
    entity_descriptor.sp_sso_descriptor = sp_sso_descriptor

    entity_descriptor
  end
```

Make sure you change values to your specific case.

You can sign any message with the util function

```ruby
Saml::Util.sign_xml(entity_descriptor)
```

For the implementation of the Service Provider, you can follow the example in the readme.
