### ISSUE TITLE
Redundant use of XmlMini_REXML

### ISSUE THREAD

**Issue by truongnmt** [digidentity/libsaml#171]
On reading XML parsing code, I noticed these lines of code:

https://github.com/digidentity/libsaml/blob/e2d3e126fef84e489281efed08602202b41447eb/lib/saml/base.rb#L45-L47

Why we're using another library REXML to parse XML, while the next line:
```ruby
object = super
```
Which will call xmlmapper:

https://github.com/digidentity/xmlmapper/blob/24b38813cb461c8b6975dd553e1ffed3f32429d2/lib/xmlmapper.rb#L282-L289
```ruby
    # @param [Nokogiri::XML::Node,Nokogiri:XML::Document,String] xml the XML
    #     contents to convert into Object.
    # @param [Hash] options additional information for parsing. :single => true
    #     if requesting a single object, otherwise it defaults to retuning an
    #     array of multiple items. :xpath information where to start the parsing
    #     :namespace is the namespace to use for additional information.
    #
    def parse(xml, options = {})
```

XMLMapper can receive String as a parameter type as well, why we need to use REXML to parse XML string? Besides, I don't see the parsed result by REXML is used anywhere.

**Comment by benoist** [comment]
This was due to a security issue with entity expansion that wasn't fixed in Nokogiri but was fixed in rexml.

If a hacker tried to disrupt the service, they could construct a message that would cause the memory to blow up and take down the service. With the Rexml line, such a message would raise an exception without causing the memory bloat.

**Comment by truongnmt** [comment]
https://github.com/sparklemotion/nokogiri/issues/1703

Seem to be this issue. I see. Thanks for your explaination!
