### ISSUE TITLE
verify_xml gives errors after signing

### ISSUE THREAD

**Issue by jonathan** [digidentity/libsaml#37]
Here is the gist with code to reproduce: https://gist.github.com/jonathan/7951578

Key, certificate, and provider need to be set up accordingly.

**Comment by sahild** [comment]
@jonathan @benoist i am able to reproduce with 100% success rate.
i was able to track it down to this line 
https://github.com/digidentity/libsaml/blob/master/lib/saml/util.rb#L113 .

So basically if i replace it with:
`message.provider.verify(signature_algorithm, signature, data, nil )`

It works out just fine by picking up the default certificate.

the issue seems to be with this method here:
https://github.com/digidentity/libsaml/blob/master/lib/saml/provider.rb#L39
its returning nil certificate.

i am happy to use `message.provider.verify(signature_algorithm, signature, data, nil )`
as i already have signing certificate from the client stored with me in the identity provider config( and same certificate is to be used to sign assertion and response ), but wanted to share my findings with you guys.
Thanks and Regards
Sahil Dhankhar

**Comment by sahild** [comment]
and since i am able to reproduce it with 100% success rate, something inside me is say that i may be doing something foolish :)
